{% set name = "vesin" %}
{% set version = "0.3.3" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a3685959e6a7b416f0347afcd99896c299a8a8430f815f91c499b062e135754

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
    - python  # [build_platform != target_platform]
    - setuptools  # [build_platform != target_platform]
    - wheel  # [build_platform != target_platform]
    - pip  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - vesin
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Computing neighbor lists for atomistic system
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/Luthaf/vesin
  doc_url: https://luthaf.fr/vesin/

extra:
  recipe-maintainers:
    - Luthaf
